### ISSUE TITLE
Unable to find the terragrunt version below 0.13.24

### ISSUE THREAD

**Issue by saimak** [warrensbox/terragrunt-switcher#17]
The version switch list is not showing versions below 0.13.24, can we have more versions populated in the list.

**Comment by bjbishop** [comment]
This would be great to include, this is a useful tool!

**Comment by warrensbox** [comment]
Hey Saima, I looked at this with Mike and Bryan. The GET API for the list of releases only returns the first page. We would need to figure out the number of pages that were paginated and loop through it to get the older version. 
I will look into fixing this bug this week.

**Comment by warrensbox** [comment]
This this should be fixed with version 0.1.165 .  
Upgrade to a latest version by : `brew upgrade warrensbox/tap/tfswitch`
Merge to release complete:
https://github.com/warrensbox/terragrunt-switcher/pull/19
